# Generated by Django 4.2.11 on 2024-03-17 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code_country', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Code Nationalité')),
                ('country', models.CharField(max_length=50, unique=True, verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Code Devise')),
                ('currency', models.CharField(max_length=50, unique=True, verbose_name='Devise et Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='LegalForm',
            fields=[
                ('code_lf', models.IntegerField(primary_key=True, serialize=False, verbose_name='Code FJ')),
                ('lf_name', models.CharField(max_length=20, unique=True, verbose_name='Sigle')),
                ('full_lf_name', models.CharField(max_length=300, verbose_name='Forme Juridique')),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('code_nationality', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Code Pays')),
                ('nationality', models.CharField(max_length=50, unique=True, verbose_name='Nationalité')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalNationality',
            fields=[
                ('code_nationality', models.CharField(db_index=True, max_length=3, verbose_name='Code Pays')),
                ('nationality', models.CharField(db_index=True, max_length=50, verbose_name='Nationalité')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical nationality',
                'verbose_name_plural': 'historical nationalitys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLegalForm',
            fields=[
                ('code_lf', models.IntegerField(db_index=True, verbose_name='Code FJ')),
                ('lf_name', models.CharField(db_index=True, max_length=20, verbose_name='Sigle')),
                ('full_lf_name', models.CharField(max_length=300, verbose_name='Forme Juridique')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical legal form',
                'verbose_name_plural': 'historical legal forms',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGroup',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nom du Groupe')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical group',
                'verbose_name_plural': 'historical groups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCurrency',
            fields=[
                ('currency_code', models.CharField(db_index=True, max_length=3, verbose_name='Code Devise')),
                ('currency', models.CharField(db_index=True, max_length=50, verbose_name='Devise et Pays')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical currency',
                'verbose_name_plural': 'historical currencys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCountry',
            fields=[
                ('code_country', models.CharField(db_index=True, max_length=3, verbose_name='Code Nationalité')),
                ('country', models.CharField(db_index=True, max_length=50, verbose_name='Pays')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical country',
                'verbose_name_plural': 'historical countrys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Raison Sociale')),
                ('adresse', models.TextField(max_length=300, null=True, verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=50, null=True, verbose_name='Code Postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('national_law', models.BooleanField(default=True, verbose_name='De Droit National ?')),
                ('ice', models.CharField(blank=True, max_length=15, null=True, verbose_name='ICE')),
                ('identifiant_fiscal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Identifiant Fiscal')),
                ('cnss', models.CharField(blank=True, max_length=10, null=True, verbose_name='Num Affiliation CNSS')),
                ('rc', models.CharField(blank=True, max_length=10, null=True, verbose_name='Num Registre de Commerce')),
                ('tp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Num Taxe Professionnelle')),
                ('class_tp', models.IntegerField(choices=[(30, 'Classe_1 (30%)'), (20, 'Classe_2 (20%)'), (10, 'Classe_3 (10%)')], default=20, verbose_name='Classe TP')),
                ('activity', models.TextField(max_length=300, null=True, verbose_name='Activité')),
                ('fiscal_year', models.IntegerField(choices=[(1, 'Décembre'), (2, 'Janvier'), (3, 'Février'), (4, 'Mars'), (5, 'Avril'), (6, 'Mai'), (7, 'Juin'), (8, 'Juillet'), (9, 'Août'), (10, 'Septembre'), (11, 'Octobre'), (12, 'Novembre')], default=1, verbose_name="Mois d'Ouverture Année Fiscale")),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Date de Création')),
                ('share_capital', models.FloatField(blank=True, verbose_name='Capital Social')),
                ('nominal_value', models.FloatField(blank=True, verbose_name='Valeur Nominale')),
                ('statut', models.IntegerField(choices=[(0, 'En Attente'), (1, 'Actif'), (2, 'Suspendu'), (3, 'InActif')], default=0, verbose_name='Statut')),
                ('terminate_date', models.DateField(blank=True, null=True, verbose_name='Date de Cessation/Dissolution')),
                ('liquidation_date', models.DateField(blank=True, null=True, verbose_name='Date de Liquidation')),
                ('logo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Joindre Logo')),
                ('file_rc', models.TextField(blank=True, max_length=100, null=True, verbose_name='Joindre Extrat RC')),
                ('file_if', models.TextField(blank=True, max_length=100, null=True, verbose_name='Joindre Bulletin IF')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, default='212', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='office.country', verbose_name='Pays')),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, default='MAD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='office.currency', verbose_name='Devise')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='office.group', verbose_name='Groupe')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('legal_form', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='office.legalform', verbose_name='Forme Juridique')),
                ('nationality', models.ForeignKey(blank=True, db_constraint=False, default='212', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='office.nationality', verbose_name='Nationalité')),
            ],
            options={
                'verbose_name': 'historical company',
                'verbose_name_plural': 'historical companys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Raison Sociale')),
                ('adresse', models.TextField(max_length=300, null=True, verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=50, null=True, verbose_name='Code Postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('national_law', models.BooleanField(default=True, verbose_name='De Droit National ?')),
                ('ice', models.CharField(blank=True, max_length=15, null=True, verbose_name='ICE')),
                ('identifiant_fiscal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Identifiant Fiscal')),
                ('cnss', models.CharField(blank=True, max_length=10, null=True, verbose_name='Num Affiliation CNSS')),
                ('rc', models.CharField(blank=True, max_length=10, null=True, verbose_name='Num Registre de Commerce')),
                ('tp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Num Taxe Professionnelle')),
                ('class_tp', models.IntegerField(choices=[(30, 'Classe_1 (30%)'), (20, 'Classe_2 (20%)'), (10, 'Classe_3 (10%)')], default=20, verbose_name='Classe TP')),
                ('activity', models.TextField(max_length=300, null=True, verbose_name='Activité')),
                ('fiscal_year', models.IntegerField(choices=[(1, 'Décembre'), (2, 'Janvier'), (3, 'Février'), (4, 'Mars'), (5, 'Avril'), (6, 'Mai'), (7, 'Juin'), (8, 'Juillet'), (9, 'Août'), (10, 'Septembre'), (11, 'Octobre'), (12, 'Novembre')], default=1, verbose_name="Mois d'Ouverture Année Fiscale")),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Date de Création')),
                ('share_capital', models.FloatField(blank=True, verbose_name='Capital Social')),
                ('nominal_value', models.FloatField(blank=True, verbose_name='Valeur Nominale')),
                ('statut', models.IntegerField(choices=[(0, 'En Attente'), (1, 'Actif'), (2, 'Suspendu'), (3, 'InActif')], default=0, verbose_name='Statut')),
                ('terminate_date', models.DateField(blank=True, null=True, verbose_name='Date de Cessation/Dissolution')),
                ('liquidation_date', models.DateField(blank=True, null=True, verbose_name='Date de Liquidation')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='files/office/company/logo', verbose_name='Joindre Logo')),
                ('file_rc', models.FileField(blank=True, null=True, upload_to='files/office/company/rc', verbose_name='Joindre Extrat RC')),
                ('file_if', models.FileField(blank=True, null=True, upload_to='files/office/company/if', verbose_name='Joindre Bulletin IF')),
                ('country', models.ForeignKey(default='212', null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.country', verbose_name='Pays')),
                ('currency', models.ForeignKey(default='MAD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.currency', verbose_name='Devise')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.group', verbose_name='Groupe')),
                ('legal_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.legalform', verbose_name='Forme Juridique')),
                ('nationality', models.ForeignKey(blank=True, default='212', null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.nationality', verbose_name='Nationalité')),
            ],
        ),
    ]
